// CRUD actions for Role resource API
export const SET_ROLE_CREATED = 'SET_ROLE_CREATED';
export const SET_ROLE_COLLECTION_RETRIEVED = 'SET_ROLE_COLLECTION_RETRIEVED';
export const SET_ROLE_RETRIEVED = 'SET_ROLE_RETRIEVED';
export const SET_ROLE_UPDATED = 'SET_ROLE_UPDATED';
export const SET_ROLE_DELETED = 'SET_ROLE_DELETED';

// Action types for Role modal UI
export const SET_ROLE_EDIT_MODAL_OPENED = 'SET_ROLE_EDIT_MODAL_OPENED';
export const SET_ROLE_DELETE_MODAL_OPENED = 'SET_ROLE_DELETE_MODAL_OPENED';
