version: '2' # required to adjust maintainability checks
checks:
    method-complexity:
        config:
            threshold: 30 # updated (default is 5)
    method-lines:
        enabled: false
# Ref: https://docs.codeclimate.com/docs/advanced-configuration
